# Generated by Django 3.2.3 on 2021-05-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='altupdate',
            name='average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='altupdate',
            name='health_msg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='altupdate',
            name='maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='altupdate',
            name='minimum',
            field=models.FloatField(null=True),
        ),
    ]
