# Generated by Django 3.2.3 on 2021-05-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altitude', '0002_auto_20210523_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAltUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('altitude', models.FloatField()),
                ('minimum', models.FloatField(null=True)),
                ('maximum', models.FloatField(null=True)),
                ('average', models.FloatField(null=True)),
                ('health_msg', models.CharField(max_length=250, null=True)),
                ('set', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
